app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path
from . import views


app_name='blogs'

urlpatterns = [
    path('news/', views.news, name='news'),
    path('new-art/', views.new_art, name='new_art'),
    path('article/detail/<int:article_id>/', views.article_detail, name='article_detail'),
    path('personal-aricle/', views.personal_article, name='personal_article'),
    path('delete-article/<int:article_id>', views.delete_article, name='delete_article'),
    path('delete-comment/<int:comment_id>', views.delete_comment, name='delete_comment'),
]

blogs/models.py
from django.db import models
from users.models import User


class section(models.Model):
    section_name = models.CharField("Название раздела", max_length=50)

    def __str__(self):
        return self.section_name

    class Meta:
        verbose_name = "Раздел"
        verbose_name_plural = "Разделы"


class article(models.Model):
    title_article = models.CharField("Название статьи", max_length=90)
    section_id = models.ForeignKey(section, null=True, verbose_name='Раздел', on_delete=models.PROTECT)
    text_article = models.TextField("Статья")
    date_publish = models.DateTimeField("Дата публикации", auto_now_add=True, null=True, blank=True)
    image = models.ImageField(upload_to='photoForArticle', null=True, blank=True)
    user_creator = models.ForeignKey(User, verbose_name='Создатель статьи', on_delete=models.PROTECT)
    

    def __str__(self):
        return self.title_article   

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"





class comment(models.Model):
    article_id = models.ForeignKey(article, on_delete=models.CASCADE)
    user_message = models.ForeignKey(User, verbose_name='Создатель комментария', on_delete=models.PROTECT)
    comment_text = models.TextField("Текст комментария", max_length=200)
    comment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Коментарий"
        verbose_name_plural = "Коментарии"

    def __str__(self):
        return f'{self.user_message.username} | {self.article_id.title_article} | {self.comment_text[:30]}'

blogs/forms.py
from django import forms

from blogs.models import article, section, comment

class UserCreateArtForm(forms.ModelForm):
    title_article = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Введите название статьи'
    }))
    text_article = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control area-for-txtart ', 'placeholder': 'Введите текст статьи'
    }))
    image = forms.ImageField(widget=forms.ClearableFileInput(
        attrs={'class': 'custom-file-input',
               'id': 'image-upload',
               'multiplay': True,
               }),
        required=False
    )
    section_id = forms.ModelChoiceField(queryset=section.objects.all())
    
    
    class Meta:
        model = article
        fields = ("title_article", "text_article", "image", "section_id")


class UserCreateCommentForm(forms.ModelForm):
    comment_text = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control com-for-art ',
        'oninput': 'autoResize(this)',
        'placeholder': 'Напиши мысли о том, как скелеты могут быть настолько плохими пловцами?'
    }))


    class Meta:
        model = comment
        fields = ("comment_text",)
        
        
    

blogs/views.py
from django.contrib import messages
from django.shortcuts import HttpResponseRedirect, render, get_object_or_404
from .forms import UserCreateArtForm, UserCreateCommentForm
from .models import section, article, comment


def news(request):
    context = {
        'title': 'Новости',
        'sections': section.objects.all(),
        'articles': article.objects.all(),
        'comments': comment.objects.all(),
    }
    return render(request, 'blogs/news.html', context)


def new_art(request):
    if request.method == "POST":
        form = UserCreateArtForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.user_creator = request.user
            form.save()
            messages.success(request, 'Вы успешно создали статью!')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        form = UserCreateArtForm()
    context = {
        'title': "Новая статья",
        'form': form,
        'sections': section.objects.all(),
    }
    return render(request, 'blogs/new_article.html', context)


def article_detail(request, article_id):
    article_detail = get_object_or_404(article, id=article_id)
    comment_for_art = comment.objects.filter(article_id = article_id)
    if request.method == 'POST':
        form = UserCreateCommentForm(data=request.POST)
        if form.is_valid():
            form.instance.user_message = request.user
            print(request.user)
            form.instance.article_id = article_detail
            
            form.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        form = UserCreateCommentForm()
    print(reversed(comment_for_art))
    context = {
        'article': article_detail,
        'comment': comment_for_art,
        'form': form
    }
    return render(request, 'blogs/article_detail.html', context)


def personal_article(request):
    articles = article.objects.filter(user_creator=request.user)
    context = {
        'title': 'Мои статьи',
        'articles': articles,
    }
    return render(request, 'blogs/personal_article.html', context)


def delete_article(request, article_id):
    print(request.META)
    article_persone = article.objects.get(id=article_id)
    if article_persone.user_creator == request.user:
        article_persone.delete()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    
    
def delete_comment(request, comment_id):
    comment_ = comment.objects.get(id=comment_id)
    if comment_.user_message == request.user:
        comment_.delete()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

blogs/templates/blogs/NETROGAY_article_detail.html
{% extends 'main/layout.html' %}
{% load static %}

{% block content %}
    <div class="blockmain">
        <div class="headname">
            <p>Новости</p>
        </div>
    </div>
    <div class="block_main_1">
        <div class="post-wrap">
            <div class="post-item">
                <div class="item-content">
                    <div class="item-icon-group"></div>
                    <div class="item-body">
                        <div class="row">
                            <h3><big>{{ article.title_article }}</big></h3>
                            <div class='from-name'><p>От: {{ article.user_creator.username }}</p></div>
                        </div>
                        <div class="text_new">
                            <p>{{ article.text_article }}</p>
                        </div>
                        {% if article.image %}
                            <hr/>
                            <center>
                                <img class="img_for_art" src="{{ item.image.url }}">
                            </center>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blogs/templates/blogs/article_detail.html
{% extends 'main/layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
{% endblock %}

{% block content %}

<style>
    .com-for-art{
        flex:1; 
        width:880px; 
        height: 45px; 
        resize: none;
    }

    .but_cust {
        text-decoration: none;
        outline: none;
        display: inline-block;
        position: relative;
        padding: 10px 30px;
        border: 2px solid #f1c40f;
        background-color: #ffffff00;
        color: #f1c40f;
        font-family: 'Montserrat', sans-serif;
        transition: .4s;
        margin-left: 5px;
        font-family: 'Montserrat Alternates', sans-serif;
    }

    .but_cust:hover {
        background-color: #c6a68978;
    }

    .form-group {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
    }

    #comment {
        display: flex;
        flex-direction: column;
        background: linear-gradient(135deg, #01706b 0%, #0e447a 100%);
        padding: 20px;
        border-radius: 10px;
    }

    #comment label {
        font-weight: bold;
        font-size: 18px;
        margin-bottom: 10px;
        color: #F5E2CD;
    }

    #comment textarea {
        font-size: 16px;
        padding: 10px;
        border-radius: 5px;
        border: none;
        background: rgb(202, 202, 202);
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
        {% comment %} width: 100%; {% endcomment %}
        {% comment %} height: 150px; {% endcomment %}
        resize: none;
    }

    .text_comment{
        word-wrap: break-word;
        width: 1040px;
    }
</style>

<div class="blockmain">
    <div class="headname">
        <p>Новости</p>
    </div>
</div>
<div class="block_main_1">
    <div class="post-wrap">
        <div class="post-item">
            <div class="item-content">
                <div class="item-icon-group"></div>
                <div class="item-body">
                    <div class="row">
                        <h3><big>{{ article.title_article }}</big></h3>
                        <div class='from-name'>
                            <p>От: {{ article.user_creator.username }}</p>
                        </div>
                    </div>
                    <div class="text_new">
                        <p>{{ article.text_article|linebreaksbr|urlize }}</p>
                    </div>
                    {% if article.image %}
                    <hr />
                    <center>
                        <img class="img_for_art" src="{{ article.image.url }}">
                    </center>
                    {% endif %}
                    <hr />
                    <form action="" id="comment" method="post" style="text-align: left; float: none; margin-top: 15px;">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="comment" style="display:block;">Комментарий:</label>
                            <div style="display:flex; align-items:center;">
                                {{ form.comment_text }}
                                {% comment %} <textarea class="form-control com-for-art" id="comment" name="comment"
                                    placeholder="Введите ваш комментарий"
                                    oninput="autoResize(this)"></textarea>  {% endcomment %}
                                <button type="submit" class="but_cust">Отправить</button>
                            </div>
                        </div>
                    </form>
                    <br>
                    <div class="comment" id="comment" style="border-radius: 10px 10px 0 0;">
                        <h1>Пользователи думают:</h1>
                    </div>
                    <br>
                    <div class="comment" id="comment" style="border-radius: 0 0 10px 10px;">
                        {% if comment %}
                            {% for com in comment|slice:"::-1" %}
                                <div class="comment_block">
                                    <div class="persona_for_com">
                                        <img style="border-radius: 20px"
                                        src=" {% if com.user_message.image %} {{ com.user_message.image.url }} {% else %} http://static.physoc.org/app/uploads/2019/10/09133258/Honorary-Members-placeholder.jpg {% endif %}" weight="40px" height="40px">
                                        
                                    </div>
                                    <div class="text_com">
                                        <p class="username-for-comment">{{ com.user_message.username }}</p>
                                        <p class="text_comment">{{ com.comment_text|linebreaksbr }}</p>
                                    </div>
                                    <div class="last-row" style="{% if com.user_message == request.user %}justify-content: space-between;{% else %}flex-direction: row;{% endif %}">
                                        <p style="float: right;">{{ com.comment_date }}</p>
                                        {% if com.user_message == request.user %}
                                            <a href="{% url 'blogs:delete_comment' com.id %}" title='Удалить комментарий'><i style="font-size: 17px;" class="fa fa-trash-o" aria-hidden="true"></i></a>
                                        {% endif %}
                                    </div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <p>На данный момент комментраиев к данной статье не существует.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<script>
    function autoResize(element) {
        element.style.height = "45px";
        element.style.height = (element.scrollHeight) + "px";
        element.style.width = "880px";
        element.style.width = (element.scrollWidth) + "px";
    }
</script>
{% endblock %}

blogs/templates/blogs/new_article.html
{% extends 'main/layout.html' %}
{% load static %}

{% block content %}
<div class="blockmain">
    <div class="headname">
        <p>Новая статья</p>
    </div>
</div>
<div class="block_main_1">
    <div class="post-wrap">
        {% if messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert"
                        style="margin-top: -8px;">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}
        <form class="form-block form-art" action="{% url 'blogs:new_art' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-item">
                <label for="{{ form.title_article.id_for_label }}">Название статьи:</label>
                {{ form.title_article }}
            </div>
            <div class="form-item">
                <label for="{{ form.text_article.id_for_label }}">Текст статьи:</label>
                {{ form.text_article }}
            </div>
            <div class="form-item photo" style='margin-top: 30px'>
                <label class="custom-file-upload" for="{{ form.image.id_for_label }}">Выберите изображение для статьи:</label>
                {{ form.image }}
            </div>
            <div class="form-item" style='margin-top: 30px'>
                <label for="{{ form.section_id.id_for_label }}">Выберите раздел подходящий вашей статье:</label>
                {{ form.section_id }}
            </div>

            <input class='custom-bsave' type="submit" value="Сохранить">
        </form>
    </div>
</div>
{% endblock %}

blogs/templates/blogs/news.html
{% extends 'main/layout.html' %}
{% load static %}

{% block content %}
    <div class="blockmain">
        <div class="headname">
            <p>Новости</p>
        </div>
    </div>
    <div class="block_main_1">

        {% if not articles %}
            <div class="post-wrap">
                <p class="no_art">В данный момент на сайте нет опубликованных пользователями статей</p>
            </div>
        {% endif %}

        {% for item in articles|slice:"::-1" %}
        <div class="post-wrap">
            <div class="post-item">
                <div class="item-content">
                    <div class="item-icon-group"></div>
                    <div class="item-body">
                        <div class="row">
                            <h3><big>{{ item.title_article }}</big></h3>
                            <div class='from-name'><p>От: {{ item.user_creator.username }}</p></div>
                        </div>
                        <div class="text_new">
                            <p>{{ item.text_article|slice:":500"|linebreaksbr|urlize }}{% if item.text_article|length > 500 %}...{% endif %}</p>
                            <div class="buttons_for_article">
                                <button class="button_news">
                                    <a class="btn" href="{% url 'blogs:article_detail' item.id %}"><span>Читать подробно</span></a>
                                </button>
                            </div>
                        </div>
                        
                        {% if item.image %}
                        <hr>
                        <center>
                            <img class="img_for_art" src="{{ item.image.url }}">
                        </center>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

blogs/templates/blogs/personal_article.html
{% extends 'main/layout.html' %}
{% load static %}

{% block content %}
    <div class="blockmain">
        <div class="headname">
            <p>Мои статьи</p>
        </div>
    </div>
    <div class="block_main_1">
        {% if not articles %}
            <div class="post-wrap">
                <p class="no_art">В данный момент Вы не написали ни одну статью</p>
            </div>
        {% endif %}
        {% for item in articles|slice:"::-1" %}
        <div class="post-wrap">
            <div class="post-item">
                <div class="item-content">
                    <div class="item-icon-group"></div>
                    <div class="item-body">
                        <div class="row">
                            <h3><big>{{ item.title_article }}</big></h3>
                            <div class='from-name'><p>От: {{ item.user_creator.username }}</p></div>
                        </div>
                        <div class="text_new">
                            <p>{{ item.text_article|slice:":500"|linebreaksbr|urlize }}{% if item.text_article|length > 500 %}...{% endif %}</p>
                        </div>

                        <div class="buttons_for_article">
                            {% if user == item.user_creator %}
                                <button class="button_delete">
                                    <a class="btn_delete" href="{% url 'blogs:delete_article' item.id %}"><span>Удалить статью</span></a>
                                </button>
                            {% endif %}
                                <button class="button_news">
                                    <a class="btn" href="{% url 'blogs:article_detail' item.id %}"><span>Читать подробно</span></a>
                                </button>
                        </div>
                        
                        {% if item.image %}
                        <hr>
                        <center>
                            <img class="img_for_art" src="{{ item.image.url }}">
                        </center>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}