app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path
from . import views


app_name='blogs'

urlpatterns = [
    path('news/', views.news, name='news'),
    path('new-art/', views.new_art, name='new_art'),
    path('article/detail/<int:article_id>/', views.article_detail, name='article_detail'),
    path('personal-aricle/', views.personal_article, name='personal_article'),
    path('delete-article/<int:article_id>', views.delete_article, name='delete_article'),
    path('delete-comment/<int:comment_id>', views.delete_comment, name='delete_comment'),
]

main/urls.py
from django.urls import path
from . import views


app_name='main'

urlpatterns = [
    path('', views.index, name='index'),
    path('achivments/', views.achivments, name='achivments'),
    path('items/chests/', views.items_chests, name='items_chests'),
    path('items/weapons/', views.items_weapons, name='items_weapons'),
    path('npc/', views.npc, name='npc'),
    path('ships/', views.ships, name='ships'),
    path('storytellings/seasons/', views.storytellings_seasons, name='storytellings_seasons'),
    path('storytellings/TallTales/', views.storytellings_TallTales, name='storytellings_TallTales')
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name='users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

main/views.py
from django.shortcuts import render


def index(request):
    context = {
        'title': 'Главная'
    }
    return render(request, 'main/index.html', context)


def achivments(request):
    context = {
        'title': 'Достижения'
    }
    return render(request, 'main/achivments.html', context)


def items_chests(request):
    context = {
        'title': 'Сундуки'
    }
    return render(request, 'main/items_chests.html', context)

def items_weapons(request):
    context = {
        'title': 'Оружие'
    }
    return render(request, 'main/items_weapons.html', context)


def npc(request):
    context = {
        'title': 'Существа'
    }
    return render(request, 'main/npc.html', context)


def ships(request):
    context = {
        'title': 'Корабли'
    }
    return render(request, 'main/ships.html', context)


def storytellings_seasons(request):
    context = {
        'title': 'Сезоны'
    }
    return render(request, 'main/storytellings_seasons.html', context)

def storytellings_TallTales(request):
    context = {
        'title': 'TallTales'
    }
    return render(request, 'main/storytellings_TallTales.html', context)

main/templates/main/achivments.html
{% extends 'main/layout.html' %}
{% load static %}
{% block content %}
    <div class="blockmain">
        <div class="headname">
            <p>Достижения</p>
        </div>
    </div>
    <div class="block_main_1">
        <div class="post-wrap">
            <div class="post-item">
                <div class="item-content">
                    <div class="item-icon-group"></div>
                    <div class="item-body">
                        <h3>Достижения</h3>
                        <p>Достижения - это задания для Xbox и Steam, которые отслеживаются и отображаются за пределами
                            Sea of Thieves.
                            За них игроку начисляется сумма Gamerscore на аккаунт Xbox и разблокируются иллюстрации,
                            которые можно использовать
                            в качестве обоев. В Steam игроки могут отображать свои заработанные достижения в разделе
                            "Демонстрация достижений"
                            своего профиля игрока. Любые достижения, которые игроки разблокируют в своей учетной записи
                            Xbox, будут синхронизированы
                            с их учетной записью Steam при входе в игру в Steam.

                            Их не следует путать с поощрениями в Sea of Thieves, которые представляют собой
                            внутриигровые испытания,
                            вознаграждающие игроков игровыми титулами, валютой и косметикой.</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="post-wrap">
            <div class="post-item">
                <div class="item-content">
                    <div class="item-icon-group"></div>
                    <div class="item-body">
                        <h3>Благодарности</h3>
                        <p>Награды - это система достижений Sea of Thieves, и они присуждаются после выполнения
                            определенных требований. Список похвал для каждой фракции можно просмотреть на странице
                            вашей репутации (после открытия страницы выберите фракцию, чтобы просмотреть ее список).
                            Большинство похвал компании имеют пять степеней, с повышением требований к более высоким
                            степеням. Однако эти требования являются кумулятивными; это означает, что достигнутый
                            прогресс также будет учитываться при определении будущих оценок.

                            Некоторые благодарности открывают косметику или названия для покупки или немедленного
                            использования. Другие благодарности могут давать дублоны. Все похвалы, перечисленные в
                            разделе "Определенная компания", вознаградят вас небольшим количеством репутации, для
                            оцененных похвал это вознаграждается один раз за оценку.

                            Если не указано иное, титулы и косметика вознаграждаются только при достижении максимального
                            уровня похвалы.</p>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

main/templates/main/index.html
{% extends 'main/layout.html' %}
{% load static %}
{% block content %}

  <div class="blure">
    <b>
      <p align="center">Игроки Создают <br> Истории Вместе</p>
  </div>
  <div class="bigbody">
  </div>
  <div class="main">
    <div class="block1">
      <img src="{% static 'main/img/photo1.png' %}" width="950" height="570">
      <p><b>Sea of Thieves — кооперативная многопользовательская компьютерная игра в жанре приключенческого боевика с
          пиратской тематикой, разработанная компанией Rare и издаваемая Microsoft Studios.</p>
      <div class="photo2">
        <img src="{% static 'main/img/photo2.png' %}" width="437" height="328">
      </div>
      <div class="myslider">
        <div class="slider">
          <div class="slider__wrapper">
            <div class="slider__items">
              <div class="slider__item">
                <div class="slider__item_inner">
                  <span class="slider__item_img">
                    <img class="slider__item_photo" src="{% static 'main/img/photosliderbackground.png' %}" alt="">
                  </span>
                  <span class="slider__item_testimonial">
                    <span class="slider__item_name">Джо Нит</span>
                    <span class="slider__item_post">Исполнительный продюсер Sea of Thieves</span>
                    <span class="slider__item_text">
                      «Игроки Создают Истории Вместе» действительно было первым названием питча — ещё до того, как мы
                      выбрали пиратскую тематику. Это самое сложное: уловить, что ты хочешь сделать и почему.
                    </span>
                  </span>
                </div>
              </div>
              <div class="slider__item">
                <div class="slider__item_inner">
                  <span class="slider__item_img">
                    <img class="slider__item_photo" src="{% static 'main/img/photosliderbackground.png' %}" alt="">
                  </span>
                  <span class="slider__item_testimonial">
                    <span class="slider__item_name">Майк Чепмен</span>
                    <span class="slider__item_post">Дизайн-директор Sea of Thieves</span>
                    <span class="slider__item_text">
                      Сабля всегда остаётся саблей. Пистоль всегда остаётся пистолем. Суть игры не в повышении их
                      характеристик.
                    </span>
                  </span>
                </div>
              </div>
              <div class="slider__item">
                <div class="slider__item_inner">
                  <span class="slider__item_img">
                    <img class="slider__item_photo" src="{% static 'main/img/photosliderbackground.png' %}" alt="">
                  </span>
                  <span class="slider__item_testimonial">
                    <span class="slider__item_name">Джо Нит</span>
                    <span class="slider__item_post">Исполнительный продюсер Sea of Thieves</span>
                    <span class="slider__item_text">
                      Наша игра это инструмент для создания дружбы. Мы хотим сделать как можно больше незнакомцев
                      друзьями.
                    </span>
                  </span>
                </div>
              </div>
              <div class="slider__item">
                <div class="slider__item_inner">
                  <span class="slider__item_img">
                    <img class="slider__item_photo" src="{% static 'main/img/photosliderbackground.png' %}" alt="">
                  </span>
                  <span class="slider__item_testimonial">
                    <span class="slider__item_name">Майк Чепмен</span>
                    <span class="slider__item_post">Дизайн-директор Sea of Thieves
                    </span>
                    <span class="slider__item_text">
                      В первой же сессии игроки придумали, что могут сделать его [Сундук Скорби] оружием. Они могли бы
                      проникнуть на корабль врага, спрятать сундук, и потом противник бегал бы в ярости по кораблю, ища
                      пробоины, вместе с этим опускаясь на дно.
                    </span>
                  </span>
                </div>
              </div>
            </div>
          </div>
          <a class="slider__control slider__control_prev" href="#" role="button" data-slide="prev"></a>
          <a class="slider__control slider__control_next" href="#" role="button" data-slide="next"></a>
        </div>
      </div>
    </div>
    <div class="bigbodyend">
    </div>
  </div>


{% endblock %}

main/templates/main/items_chests.html
{% extends 'main/layout.html' %}
{% load static %}
{% block content %}

    <div class="sub_blockmain">
        <div class="headname">
            <p>Предметы</p>
        </div>
        <div class="sub_headname">
            <p><small>Сундуки</small></p>
        </div>
    </div>
    <div class="block_main_1">
        <div class="post-wrap">
            <div class="post-item">
                <div class="item-content">
                    <div class="item-icon-group"></div>
                    <div class="item-body">
                        <img src="{% static 'main/img/Сундуки_с_сокровищами.jpg' %}" alt="1"
                             style="margin-right: 50px;float:left;width: 175px; height: 175px;margin-bottom:35px;margin-top: 15px;" />
                        <h3><big>Сундуки с сокровищами</big></h3>

                        <p><big> Сундук с сокровищами — один из типов сокровищ в Sea of Thieves. Найти их можно по всему миру игры.
                            Эти сундуки заперты на волшебные неразрушимые замки, открыть которые могут только Златодержцы при помощи хранящихся
                            у них отмычек. За сундуки представители Златодержцев в форпостах готовы предложить игрокам золото, репутацию и бонус
                            к степени эмиссарства.</p>


                            <p>Игрок может переносить только один сундук за раз. При переноске невозможно использовать предметы и бегать. Если поставить сундук, он будет испускать белый свет, что делает его заметным на большом расстоянии. Если уронить сундук в воду, он будет плавать и начнёт тонуть через пять минут. Сундуки, которые уронили на твёрдой земле или побережье, теоретически могут остаться в игре навсегда. Нетронутые сундуки исчезают, когда остров перезагружается. Сундуки, которые уронили в глубокую воду, исчезают, погрузившись на дно. Сундуки можно захватывать гарпуном.

                                У каждого обычного сундука есть пепельная и пережившая кораблекрушение версия. Пепельные сундуки можно найти в Дьявольской глотке, от обычных они отличаются жёлтым свечением. Стоят они вдвое больше обычных. Пережившие кораблекрушение сундуки можно найти либо выброшенными на берега островов, либо внутри обломков кораблей. Стоят они столько же, сколько обычные и засчитываются для получения звания "Hoarder of Barnacled Gold". Помимо обычных сундуков существуют два ценных сундука скелетов: Сундук скелета капитана и Сундук из цитадели, получить которые можно после различных столкновений в море; и один призрачный сундук, получить который можно только за уничтожение призрачных капитанских кораблей.

                                Также существуют три проклятых сундука, обладающих особыми свойствами. Сундук тысячи кружек опьяняет несущего его, Сундук скорби время от времени плачет, затапливая корабль, а Сундук ярости разогревается и может взорваться, если не окатывать его водой.
                            <p>&nbsp;</p>
                                <p><big>Где найти.</big></p>
                                Чаще всего сундуки с сокровищами можно выкопать, руководствуясь картой, которую можно получить по индивидуальному заданию или в рамках путешествия Златодержцев. Для выкапывания потребуется лопата. В зависимости от сложности задания для выкапывания сундука нужно разное количество взмахов лопатой. Когда член команды находит сундук, копая в правильном месте, все остальные члены команды получают сообщение о типе сундука и том, кто нашёл его. Отдельные сундуки можно обнаружить лежащими на берегах островов или получить в награду за различные столкновения.
                                <p>&nbsp;</p>
                                <p><big>Механика эмиссарства.</big></p>
                                Все команды, идущие в плавание в качестве Эмиссаров Златодежцев, получают степень эмиссарства, когда впервые подбирают сундук и поднимают его на борт. Степень получают и Эмиссары Костей мертвеца, поскольку они получают бонус за любое похищенное сокровище. Продажа сундуков компаниям не даёт степень эмиссарства, однако игроки получают бонус к репутации эмиссара, которая определяет положение на Ладдере. Чем выше степень эмиссарства команды, тем больше золота, репутации и репутации эмиссара она получает за продажу сундуков с сокровищами.
                            </big>
                            </p>


                    </div>
                </div>
            </div>
        </div>


    </div>
{% endblock %}

main/templates/main/items_weapons.html
{% extends 'main/layout.html' %}
{% load static %}
{% block content %}

    <div class="sub_blockmain">
        <div class="headname">
            <p>Предметы</p>
        </div>
        <div class="sub_headname">
            <p><small>Оружие</small></p>
            <s></s>
        </div>
    </div>
    <div class="block_main_1">
        <div class="post-wrap">
            <div class="post-item">
                <div class="item-content">
                    <div class="item-icon-group"></div>
                    <div class="item-body">
                        <img src="{% static 'main/img/Сабля_иконка.png' %}" alt="1"
                            style="margin-right: 50px;float:left;width: 175px; height: 175px;margin-bottom:35px;margin-top: 15px;" />

                        <h3>Сабля</h3>

                        <p>Сабля — холодное оружие, которое позволяет проводить различные приёмы. Единственное оружие ближнего боя в игре.
                            Игрок может наносить ей удары, блокировать удары противников, уворачиваться, проводить комбо из трёх ударов и
                            бросаться на противника с разбега. Это делает саблю наиболее гибким оружием, но особые неочевидные приёмы будут
                            доступны только самым искусным фехтовальщикам. Обычные удары наносят 25% урона, заряженные — 60% урона.</p>
                        <button id="button1">
                            <a class="btn"><span>Читать далее</span></a>
                        </button>
                        <div id="rect1">
                            <p>Все новые игроки по умолчанию экипированы саблей моряка. Другие варианты оформления можно купить в оружейном магазине.
                                Влияют они только на внешний вид сабли, но не на её функционал.Саблей можно нанести урон сразу нескольким противникам
                                по дуге. Для уничтожения слабейшего скелета обычного типа достаточно двух прямых ударов саблей, для уничтожения скелета
                                в задании, скелета в форте скелетов или другого игрока — 4 ударов, для уничтожения скелетов в заданиях Сокровищ Афины —
                                7 ударов.</p>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="post-wrap">
            <div class="post-item">
                <div class="item-content">
                    <div class="item-icon-group"></div>
                    <div class="item-body">
                        <img src="{% static 'main/img/Пистоль_иконка.png' %}" alt="1"
                            style="margin-right: 50px;float:left;width: 175px; height: 175px;margin-bottom:35px;margin-top: 15px;" />
                        <h3>Пистоль</h3>

                        <p>Пистоль — огнестрельное оружие, эффективное на средней дистанции. Для прицеливания используется мушка, оптического прицела
                            не имеет. Пистоль стреляет и перезаряжается быстрее, чем дальнострел, но и поражает цели на меньшей дистанции. Пули летят
                            по дуге, поэтому при стрельбе издалека целиться нужно особенно тщательно. При стрельбе от бедра точность не ухудшается,
                            что делает пистоль идеальным огнестрельным оружием для ближнего боя и сражения на средней дистанции. Один выстрел из
                            пистоля наносит 50% урона.</p>
                        <button id="button2">
                            <a class="btn"><span>Читать далее</span></a>
                        </button>
                        <div id="rect2">
                            <p>Пистоль эффективен на малой и средней дистанции. Выстреливает единственную пулю. У каждого игрока есть запас
                                боеприпасов на пять выстрелов из пистоля. Пополнить запас можно в сундуке с боеприпасами или в арсенале.
                                Пистоль обеспечивает бОльшую точность стрельбы, чем мушкетон, но меньшие точность и дальность поражения,
                                чем дальнострел, что делает его универсальным оружием. Пули, выпущенные из пистоля, летят по дуге, поэтому
                                при стрельбе по удалённым целям, нужно быть особенно осторожным. Основным преимуществом пистоля является
                                малое время перезарядки и хорошая точность при стрельбе от бедра. Выстрел из пистоля наносит 55% урона,
                                таким образом для убийства игрового пирата нужно два выстрела. Для убийства обычного скелета достаточно
                                одного выстрела, скелета в задании и форте скелетов — 2-3 выстрела, скелета в задании Сокровищ Афины — 3-5 выстрелов.
                                Для уничтожения сапфировой статуи русалки нужно 5 выстрелов из пистоля.Все новые игроки по умолчанию экипированы
                                пистолем моряка. Другие варианты оформления можно купить в оружейном магазине. Влияют они только на внешний вид пистоля,
                                но не его функционал.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="post-wrap">
            <div class="post-item">
                <div class="item-content">
                    <div class="item-icon-group"></div>
                    <div class="item-body">
                        <img src="{% static 'main/img/Мушкетон_иконка.png' %}" alt="1"
                            style="margin-right: 50px;float:left;width: 175px; height: 175px;margin-bottom:35px;" />
                        <h3>Мушкетон</h3>
                        <p>Мушкетон — огнестрельное оружие типа дробовика, выстреливающее горстью дроби. Является крайне эффективным в ближнем бою,
                            но на расстоянии теряет убойную силу. Наилучший эффект достигается, если стрелять из мушкетона прицельно, иначе дробины
                            разлетаются слишком широко. При выстреле в персонажа игрока в упор, тот погибнет. Попадание из мушкетона в ближнем бою
                            также сбивает противника с ног. Заряд состоит из 10 дробин, каждая из которых наносит 5-10% урона.</p>
                        <button id="button3">
                            <a class="btn"><span>Читать далее</span></a>
                        </button>
                        <div id="rect3">
                            <p>Мушкетон — оружие типа дробовика, особенно эффективное на ближней дистанции. Выстреливает десять дробин за раз.
                                У каждого игрока есть запас боеприпасов на пять выстрелов из мушкетона. Пополнить запас можно в сундуке с боеприпасами
                                или в арсенале. Мушкетон наносит наибольший урон при точном прицеливании и выстреле в упор. При прицельной стрельбе
                                все дробины летят в центр мишени, при стрельбе от бедра — разлетаются в разные стороны. Выстрел в упор из мушкетона
                                убивает пирата игрока с полным запасом здоровья, что делает это оружие самым смертоносным в игре. Его недостатком
                                является то, что он практически бесполезен на средней дистанции, на которой каждая дробина наносит всего 1-5% урона.
                                Тем не менее дальним выстрелом из мушкетона можно пытаться подорвать пороховую бочку. Для уничтожения обычных скелетов
                                и скелетов в фортах достаточно одного выстрела в упор из мушкетона. Для уничтожения скелетов в путешествиях Сокровищ
                                Афины потребуется 2-3 выстрела. Для разрушения сапфировой статуи русалки нужно 3 выстрела из мушкетона в упор.</p>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="post-wrap">
            <div class="post-item">
                <div class="item-content">
                    <div class="item-icon-group"></div>
                    <div class="item-body">
                        <img src="{% static 'main/img/Дальнострел_иконка.png' %}" alt="1"
                             style="margin-right: 50px;float:left;width: 175px; height: 175px;margin-bottom:35px;" />
                        <h3>Дальнострел</h3>

                        <p>Дальнострел — это дальнобойная снайперская винтовка с оптическим прицелом. Трещины в прицеле позволяют пиратам прицелиться
                            наилучшим образом. Дальнострел — идеальное оружие для устранения противников с большого расстояния. При выстреле от бедра
                            пуля скорее всего не попадёт в цель, что делает это оружие бесполезным в ближнем бою. Дальнострел очень мощное оружие,
                            выстрел из которого наносит 70% урона. Оно прекрасно подходит для отстрела скелетов на расстоянии и противников.</p><p></p>
                        <button id="button4">
                            <a class="btn"><span>Читать далее</span></a>
                        </button>
                        <div id="rect4">
                            <p>Как и в случае с подзорной трубой, линзы прицела будут отражать солнечный и лунный
                                свет, выдавая положение игрока, поэтому использовать дальнострел следует с осторожностью. Дальнострел — мощная снайперская винтовка, которая выстреливает единственную пулю и обладает большой дальностью поражения.
                                При стрельбе от бедра крайне неточен. У каждого игрока есть запас боеприпасов на пять выстрелов из дальнострела.
                                Пополнить запас можно в сундуке с боеприпасами или в арсенале. Оптический прицел действует сходным с подзорной трубой
                                образом: приближает и фокусирует видимое игроком. Однако он также отражает солнечный и лунный свет, выдавая положение
                                игрока. В прицеле нет традиционного перекрестия, его роль выполняют две перекрещивающиеся трещины. Один выстрел из
                                дальнострела наносит пирату игрока 70% урона, что значит, что убийство достаточно двух выстрелов. Как и в случае с
                                пистолем, пули, выпущенные из дальнострела, летят по небольшой дуге, при стрельбе по дальним целям необходимо учитывать
                                это и соответственным образом перемещать прицел. Для уничтожения обычных скелетов достаточно одного выстрела из
                                дальнострела, для уничтожения скелетов в заданиях и фортах — 1-3 выстрела, скелетов в заданиях Сокровищ Афины — 3-4
                                выстрела. Для уничтожения сапфировой статуи русалки потребуется 4 выстрела.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'main/css/styles.css' %}">
    <script src="https://kit.fontawesome.com/cf5ef8a0fd.js" crossorigin="anonymous"></script>
    <script src="{% static 'main/js/button-scripts.js' %}"></script>
    {% block css %}
    {% endblock %}
    <title>{{ title }}</title>
</head>
<body>
    <header>
        <div class="header_menu">
          <div class="logo">
            <a href="{% url 'main:index' %}">
              <span style="font-size: 200%;">
                <div class="logophoto">
                  <img src="{% static 'main/img/logo.png' %}" width="64" height="64">
                </div>
                Sea of Thieves Wiki
              </span>
            </a>
          </div>
            <nav class="one">
                <ul class="topmenu">
                    <li><a href="{% url 'blogs:news' %}">Новости</a></li>
                  <li><a href="{% url 'main:items_chests' %}">Предметы<i class="fa fa-angle-down"></i></a>
                  <ul class="submenu">
                    <li><a href="{% url 'main:items_chests' %}">Сундуки</a></li>
                    <li><a href="{% url 'main:items_weapons' %}">Оружие</a></li>
                  </ul>
                  </li>
                  <li><a href="{% url 'main:ships' %}">Корабли</a></li>
                  <li><a href="{% url 'main:npc' %}">Существа</a></li>
                  <li><a href="{% url 'main:storytellings_seasons' %}">Истории<i class="fa fa-angle-down"></i></a>
                    <ul class="submenu">
                        <li><a href="{% url 'main:storytellings_seasons' %}">Сезоны</a></li>
                        <li><a href="{% url 'main:storytellings_TallTales' %}">Tall Tales</a></li>
                    </ul>
                    </li>
                  <li><a href="{% url 'main:achivments' %}">Достижения</a></li>
                </ul>
              </nav>

            <div class="search">
            <form class="search-form">
              <input class="in-put" type="text" placeholder="Искать здесь...">
              <button id="button0" type="submit"></button>
            </form>
          </div>
        </div>
    </header>
    <div class="profile">
        {% if user.is_anonymous %}
            <div class="profile-headname">
                <p>Нет аккаунта?</p>
            </div>
            
            <div class="nav-profile">
                <li><a href="{% url 'users:login' %}">Войти</a></li>
                <li><a href="{% url 'users:registration' %}">Зарегистрироваться</a></li>
            </div>
        {% else %}
            <div class="profile-headname">
                <p>Профиль</p>
            </div>
            <div class="nav-profile">
                <li><a href="{% url 'users:profile' %}">Аккаунт</a></li>
                <li><a href="{% url 'blogs:new_art' %}">Создать статью</a></li>
                <li><a href="{% url 'blogs:personal_article' %}">Мои статьи</a></li>

                {% if user.is_staff %}
                    <li><a href="{% url 'admin:index' %}">Админ панель</a></li>
                {% endif %}
                <li><a href="{% url 'users:logout' %}">Выйти</a></li>
            </div>
        {% endif %}

    </div>
    {% block content %}
    {% endblock %}
</body>
</html>